const logger = require('../services/logService');
const { session } = require('electron');
const fs = require('fs/promises');
const path = require('path');

class CookiesService {
  /**
   * Exporta os cookies do Electron para o formato Netscape (cookies.txt)
   * compatível com yt-dlp e spot-dlp.
   * 
   * @param {string} filterDomain O domínio base para filtrar (ex: '.youtube.com' ou '.spotify.com')
   * @param {string} outputPath O caminho completo onde o arquivo cookies.txt será salvo
   * @param {string} partition Opcional: A partição (ex: 'persist:youtube')
   * @returns {Promise<boolean>} Sucesso
   */
  async exportNetscapeCookies(filterDomain, outputPath, partition = null) {
    try {
      const targetSession = partition ? session.fromPartition(partition) : session.defaultSession;
      const cookies = await targetSession.cookies.get({ domain: filterDomain });
      
      if (!cookies || cookies.length === 0) {
        logger.info(`Nenhum cookie encontrado para o domínio: ${filterDomain}`);
        return false;
      }

      // Cabeçalho padrão do formato Netscape HTTP Cookie File
      let content = `# Netscape HTTP Cookie File\n# This file is generated by Braga Digital Studio\n# https://curl.haxx.se/rfc/cookie_spec.html\n\n`;

      cookies.forEach(cookie => {
        // Formato: domain, includeSubdomains, path, secure, expiry, name, value
        const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const secure = cookie.secure ? 'TRUE' : 'FALSE';
        const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
        
        content += `${cookie.domain}\t${includeSubdomains}\t${cookie.path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}\n`;
      });

      await fs.writeFile(outputPath, content, 'utf8');
      logger.info(`Cookies exportados com sucesso para ${outputPath}`);
      return true;
    } catch (error) {
      logger.error('Erro ao exportar cookies:', error);
      return false;
    }
  }
}

module.exports = new CookiesService();
